### PR TITLE
commit on link

### PR DESCRIPTION
**Pull request by ronniemcbride**
User Snap #244 #245  edit and update.

### CODE REVIEW

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr164-75wykzc8hlga8al83ks3rpco6kgto9fu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e5bc2857072dc73aedaf5d

**Review by eohammond — APPROVED** [review]

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr164-75wykzc8hlga8al83ks3rpco6kgto9fu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e5bc2857072dc73aedaf5d

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr164-75wykzc8hlga8al83ks3rpco6kgto9fu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e5bc2857072dc73aedaf5d

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr164-75wykzc8hlga8al83ks3rpco6kgto9fu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e5bc2857072dc73aedaf5d

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr164-75wykzc8hlga8al83ks3rpco6kgto9fu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e5bc2857072dc73aedaf5d

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr164-75wykzc8hlga8al83ks3rpco6kgto9fu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e5bc2857072dc73aedaf5d

**Comment by eohammond** [comment]
Hey, noticing that this has been here for a few days. @ronniemcbride did you need @coreyvickery to review as well?

**Comment by ronniemcbride** [comment]
> Hey, noticing that this has been here for a few days. @ronniemcbride did you need @coreyvickery to review as well?

The update that was made @coreyvickery  had assigned to himself prior to his time off, but I went ahead and took care of them. I think Corey should have a chance to review them before I publish this page.

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr164-75wykzc8hlga8al83ks3rpco6kgto9fu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e5bc2857072dc73aedaf5d

**Review by coreyvickery — APPROVED** [review]

**Pull request merged**
