### PR TITLE
Design and content tweaks to Optimization page

### PR DESCRIPTION
**Pull request by coreyvickery**

### CODE REVIEW

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr189-pmvf57dhj8uuvgrdlpqaowoqbslgppy8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/613acc62baa70d18919ce3ca

**Comment by coreyvickery** [comment]
@dcaryll Looks like the bullets below Pattern 3 got a little screwed up, which I have a fix for. Otherwise, ready for review.

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr189-pmvf57dhj8uuvgrdlpqaowoqbslgppy8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/613acc62baa70d18919ce3ca

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr189-pmvf57dhj8uuvgrdlpqaowoqbslgppy8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/613acc62baa70d18919ce3ca

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr189-pmvf57dhj8uuvgrdlpqaowoqbslgppy8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/613acc62baa70d18919ce3ca

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr189-pmvf57dhj8uuvgrdlpqaowoqbslgppy8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/613acc62baa70d18919ce3ca

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr189-pmvf57dhj8uuvgrdlpqaowoqbslgppy8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/613acc62baa70d18919ce3ca

**Pull request merged**
