### PR TITLE
Minor text and image changes to Alert page

### PR DESCRIPTION
**Pull request by coreyvickery**
Updated copy and better quality images

### CODE REVIEW

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr156-iwryvtnutz2wfx9qzjzmfoz5lro5pmtq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60d61d12462cdfa5098e7a34

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr156-iwryvtnutz2wfx9qzjzmfoz5lro5pmtq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60d61d12462cdfa5098e7a34

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr156-iwryvtnutz2wfx9qzjzmfoz5lro5pmtq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60d61d12462cdfa5098e7a34

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr156-iwryvtnutz2wfx9qzjzmfoz5lro5pmtq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60d61d12462cdfa5098e7a34

**Review by eohammond — APPROVED** [review]

**Comment by eohammond** [comment]
Looks great @coreyvickery

**Pull request merged**
