### PR TITLE
New link page created.

### PR DESCRIPTION
**Pull request by ronniemcbride**

### CODE REVIEW

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-perbxux5r9vf0m9qkx5690ldxvjwpvz8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60db54bf57072d6291e6b99d

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-perbxux5r9vf0m9qkx5690ldxvjwpvz8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60db54bf57072d6291e6b99d

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-perbxux5r9vf0m9qkx5690ldxvjwpvz8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60db54bf57072d6291e6b99d

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-perbxux5r9vf0m9qkx5690ldxvjwpvz8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60db54bf57072d6291e6b99d

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-perbxux5r9vf0m9qkx5690ldxvjwpvz8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60db54bf57072d6291e6b99d

**Comment by eohammond** [comment]
Congrats @ronniemcbride, your first MR! it looks good. I'm not looking at the design so not sure but are the alerts supposed to be full width?

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-perbxux5r9vf0m9qkx5690ldxvjwpvz8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60db54bf57072d6291e6b99d

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-perbxux5r9vf0m9qkx5690ldxvjwpvz8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60db54bf57072d6291e6b99d

**Comment by eohammond** [comment]
@ronniemcbride @coreyvickery I've merged this in. Feel free to publish!

**Pull request merged**
