### PR TITLE
Change max width of body text from 750px to 1000px

### PR DESCRIPTION
**Pull request by coreyvickery**
Don't need a max width on body text (`p`) anymore

### CODE REVIEW

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr158-liyjayxnmeskkkg8qkysfknhssxgdzf4.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60d9f2baf543e7003f64c4b4

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr158-liyjayxnmeskkkg8qkysfknhssxgdzf4.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60d9f2baf543e7003f64c4b4

**Comment by eohammond** [comment]
@coreyvickery changing that makes the P's much wider. Is that what you want? See preview in Foundations > Overview for example: https://pr158-liyjayxnmeskkkg8qkysfknhssxgdzf4.tugboat.qa/foundations/

**Comment by coreyvickery** [comment]
@eohammond Yes, I think it looks better on this website only.

**Comment by eohammond** [comment]
Ok, merge complete @coreyvickery

**Pull request merged**
