### PR TITLE
Major updates to Components page, tweaks to other pages

### PR DESCRIPTION
**Pull request by coreyvickery**
- Replaced all Components thumbnail images with better versions
- Added new thumbnail images and page links for `Link` and `Progress steps` components
- Unified the cross-links at the bottom of the page with those of other pages
- Tweaked a few other component pages (very minor changes, too many to list)
- Wrote a few new CSS styles and hacked a few things

### CODE REVIEW

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr186-qbv4d8v7rr9tbi495zxrztifsaalbycx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6131d73d7db70c616e8823f4

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr186-qbv4d8v7rr9tbi495zxrztifsaalbycx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6131d73d7db70c616e8823f4

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr186-qbv4d8v7rr9tbi495zxrztifsaalbycx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6131d73d7db70c616e8823f4

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr186-qbv4d8v7rr9tbi495zxrztifsaalbycx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6131d73d7db70c616e8823f4

**Comment by eohammond** [comment]
@coreyvickery looks like you merged this. There are a ton of changes. Do you still need a review?

**Comment by coreyvickery** [comment]
@eohammond No need, but thanks for checking.

**Pull request merged**
