### PR TITLE
New About section, new How we build page

### PR DESCRIPTION
**Pull request by coreyvickery**
- New About section
- Adding page for 'How we build'

### CODE REVIEW

**Comment by coreyvickery** [comment]
@dcaryll @markcaron Would like your approval of this page before I merge it.

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr218-k4twlbercu2uvegu49ifcyzlgvcjscki.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61eca32fbc23b94702485be1

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr218-k4twlbercu2uvegu49ifcyzlgvcjscki.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61eca32fbc23b94702485be1

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr218-k4twlbercu2uvegu49ifcyzlgvcjscki.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61eca32fbc23b94702485be1

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr218-k4twlbercu2uvegu49ifcyzlgvcjscki.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61eca32fbc23b94702485be1

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr218-k4twlbercu2uvegu49ifcyzlgvcjscki.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61eca32fbc23b94702485be1

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr218-k4twlbercu2uvegu49ifcyzlgvcjscki.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61eca32fbc23b94702485be1

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr218-k4twlbercu2uvegu49ifcyzlgvcjscki.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61eca32fbc23b94702485be1

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr218-k4twlbercu2uvegu49ifcyzlgvcjscki.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61eca32fbc23b94702485be1

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr218-k4twlbercu2uvegu49ifcyzlgvcjscki.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61eca32fbc23b94702485be1

**Comment by coreyvickery** [comment]
@dcaryll Making sure you see this.

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr218-k4twlbercu2uvegu49ifcyzlgvcjscki.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61eca32fbc23b94702485be1

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr218-k4twlbercu2uvegu49ifcyzlgvcjscki.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61eca32fbc23b94702485be1

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr218-k4twlbercu2uvegu49ifcyzlgvcjscki.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61eca32fbc23b94702485be1

**Pull request merged**
