### PR TITLE
Made a slight tweak to how tables are displayed

### PR DESCRIPTION
**Pull request by coreyvickery**
Changed one line of CSS to alter the display of tables where I want them.

### CODE REVIEW

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr160-uz5pta4rispgjzdnlcsgehhyyovuxin4.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60dccf0b462cdfcbc69246bf

**Comment by wesruv** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr160-uz5pta4rispgjzdnlcsgehhyyovuxin4.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60dccf0b462cdfcbc69246bf

**Comment by eohammond** [comment]
@coreyvickery the only table I'm finding that is affected by this change is on the Design code status page https://pr160-uz5pta4rispgjzdnlcsgehhyyovuxin4.tugboat.qa/design-code-status/ This change makes that layout slightly different. Compare the tugboat version to the ux.redhat.com version. You good with that?

**Comment by coreyvickery** [comment]
@eohammond I see what you mean, the change to the Design/code status table does not look good. Should I delete the branch or what's the next step to deny this change? I've never had to do this before.

**Comment by coreyvickery** [comment]
@eohammond Rejecting change, so I'm closing this merge request.

**Comment by eohammond** [comment]
Thanks @coreyvickery sorry I wasn't able to address this when you asked, but I think you handled this just fine. Putting a style on `th` affects all tables on the sites. To only affect a specific instance we could assign a class to that type of table or th and create a new style for it.

**Pull request closed without merging**
