### PR TITLE
Re-export image w/ paths

### PR DESCRIPTION
**Pull request by eohammond**

### CODE REVIEW

**Comment by wesruv** [comment]
Not sure why tugboat didn't give a link to the environment it spun up for this PR, but it did make one: https://pr51-h7scz79zm9nd9hhwdqx8r2torkt1ohzn.tugboat.qa/

**Comment by eohammond** [comment]
@wesruv what is Tugboat and does it change my workflow?

**Comment by wesruv** [comment]
It will build a full version of the web site with just your changes applied. So we can check to make sure that everything looks right when it's not on our 'local'.

Just a good sanity check, doesn't have to change anything you do.

**Comment by eohammond** [comment]
Got it. Thanks @wesruv

**Pull request merged**
